language: node_js
node_js:
  - node
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - chromium-chromedriver
before_script:
  # include ChromeDriver in PATH
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  # start Chrome and listen on localhost
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - npm start